//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kisildalur.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class config : global::System.Configuration.ApplicationSettingsBase {
        
        private static config defaultInstance = ((config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new config())));
        
        public static config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("709, 530")]
        public global::System.Drawing.Size dvSize {
            get {
                return ((global::System.Drawing.Size)(this["dvSize"]));
            }
            set {
                this["dvSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224")]
        public int dvSplitWidth {
            get {
                return ((int)(this["dvSplitWidth"]));
            }
            set {
                this["dvSplitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("177")]
        public int dvLeft0Width {
            get {
                return ((int)(this["dvLeft0Width"]));
            }
            set {
                this["dvLeft0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89")]
        public int dvRight0Width {
            get {
                return ((int)(this["dvRight0Width"]));
            }
            set {
                this["dvRight0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101")]
        public int dvRight1Width {
            get {
                return ((int)(this["dvRight1Width"]));
            }
            set {
                this["dvRight1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public int dvRight2Width {
            get {
                return ((int)(this["dvRight2Width"]));
            }
            set {
                this["dvRight2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int dvRight3Width {
            get {
                return ((int)(this["dvRight3Width"]));
            }
            set {
                this["dvRight3Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380, 271")]
        public global::System.Drawing.Size fmSize {
            get {
                return ((global::System.Drawing.Size)(this["fmSize"]));
            }
            set {
                this["fmSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229")]
        public int fmtop0Width {
            get {
                return ((int)(this["fmtop0Width"]));
            }
            set {
                this["fmtop0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("538, 559")]
        public global::System.Drawing.Size kSize {
            get {
                return ((global::System.Drawing.Size)(this["kSize"]));
            }
            set {
                this["kSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("308, 320")]
        public global::System.Drawing.Size loSize {
            get {
                return ((global::System.Drawing.Size)(this["loSize"]));
            }
            set {
                this["loSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("386, 130")]
        public global::System.Drawing.Size lSize {
            get {
                return ((global::System.Drawing.Size)(this["lSize"]));
            }
            set {
                this["lSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("741, 440")]
        public global::System.Drawing.Size pSize {
            get {
                return ((global::System.Drawing.Size)(this["pSize"]));
            }
            set {
                this["pSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ptop0Width {
            get {
                return ((int)(this["ptop0Width"]));
            }
            set {
                this["ptop0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("285")]
        public int ptop1Width {
            get {
                return ((int)(this["ptop1Width"]));
            }
            set {
                this["ptop1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ptop2Width {
            get {
                return ((int)(this["ptop2Width"]));
            }
            set {
                this["ptop2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ptop3Width {
            get {
                return ((int)(this["ptop3Width"]));
            }
            set {
                this["ptop3Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ptop4Width {
            get {
                return ((int)(this["ptop4Width"]));
            }
            set {
                this["ptop4Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229")]
        public int umtop0Width {
            get {
                return ((int)(this["umtop0Width"]));
            }
            set {
                this["umtop0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("623, 398")]
        public global::System.Drawing.Size addSize {
            get {
                return ((global::System.Drawing.Size)(this["addSize"]));
            }
            set {
                this["addSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("136")]
        public int addleft0Width {
            get {
                return ((int)(this["addleft0Width"]));
            }
            set {
                this["addleft0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("623")]
        public int addSizeWidth {
            get {
                return ((int)(this["addSizeWidth"]));
            }
            set {
                this["addSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("398")]
        public int addSizeHeight {
            get {
                return ((int)(this["addSizeHeight"]));
            }
            set {
                this["addSizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int addtop2Width {
            get {
                return ((int)(this["addtop2Width"]));
            }
            set {
                this["addtop2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174")]
        public int addSplitWidth {
            get {
                return ((int)(this["addSplitWidth"]));
            }
            set {
                this["addSplitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kísildalur ehf.\r\nÁlfheimar 2 - 104 Reykjavík\r\nSími: 517 1150")]
        public string header1 {
            get {
                return ((string)(this["header1"]));
            }
            set {
                this["header1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kt. 670905-0550\r\nVSK no 87926\r\nBankanr. 0301-26-004802")]
        public string header2 {
            get {
                return ((string)(this["header2"]));
            }
            set {
                this["header2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sími: 517 1150")]
        public string header3 {
            get {
                return ((string)(this["header3"]));
            }
            set {
                this["header3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kt. 670905-0550")]
        public string header4 {
            get {
                return ((string)(this["header4"]));
            }
            set {
                this["header4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VSK no 87926")]
        public string header5 {
            get {
                return ((string)(this["header5"]));
            }
            set {
                this["header5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bankanr. 0301-26-004802")]
        public string header6 {
            get {
                return ((string)(this["header6"]));
            }
            set {
                this["header6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string mysql_host {
            get {
                return ((string)(this["mysql_host"]));
            }
            set {
                this["mysql_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kisill")]
        public string mysql_user {
            get {
                return ((string)(this["mysql_user"]));
            }
            set {
                this["mysql_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string mysql_port {
            get {
                return ((string)(this["mysql_port"]));
            }
            set {
                this["mysql_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kisill")]
        public string mysql_database {
            get {
                return ((string)(this["mysql_database"]));
            }
            set {
                this["mysql_database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int order_id {
            get {
                return ((int)(this["order_id"]));
            }
            set {
                this["order_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("856, 602")]
        public global::System.Drawing.Size settSize {
            get {
                return ((global::System.Drawing.Size)(this["settSize"]));
            }
            set {
                this["settSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int settHeight {
            get {
                return ((int)(this["settHeight"]));
            }
            set {
                this["settHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int settWidth {
            get {
                return ((int)(this["settWidth"]));
            }
            set {
                this["settWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("372")]
        public int settSplitTextbox {
            get {
                return ((int)(this["settSplitTextbox"]));
            }
            set {
                this["settSplitTextbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int mainWidth {
            get {
                return ((int)(this["mainWidth"]));
            }
            set {
                this["mainWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("410")]
        public int mainHeight {
            get {
                return ((int)(this["mainHeight"]));
            }
            set {
                this["mainHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int mainWidth0 {
            get {
                return ((int)(this["mainWidth0"]));
            }
            set {
                this["mainWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int mainWidth1 {
            get {
                return ((int)(this["mainWidth1"]));
            }
            set {
                this["mainWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int mainWidth2 {
            get {
                return ((int)(this["mainWidth2"]));
            }
            set {
                this["mainWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int mainWidth3 {
            get {
                return ((int)(this["mainWidth3"]));
            }
            set {
                this["mainWidth3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historyListWidth0 {
            get {
                return ((int)(this["historyListWidth0"]));
            }
            set {
                this["historyListWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historyListWidth1 {
            get {
                return ((int)(this["historyListWidth1"]));
            }
            set {
                this["historyListWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historyListWidth2 {
            get {
                return ((int)(this["historyListWidth2"]));
            }
            set {
                this["historyListWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historyListWidth3 {
            get {
                return ((int)(this["historyListWidth3"]));
            }
            set {
                this["historyListWidth3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historyListWidth4 {
            get {
                return ((int)(this["historyListWidth4"]));
            }
            set {
                this["historyListWidth4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historySearchWidth0 {
            get {
                return ((int)(this["historySearchWidth0"]));
            }
            set {
                this["historySearchWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historySearchWidth1 {
            get {
                return ((int)(this["historySearchWidth1"]));
            }
            set {
                this["historySearchWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historySearchWidth2 {
            get {
                return ((int)(this["historySearchWidth2"]));
            }
            set {
                this["historySearchWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historySearchWidth3 {
            get {
                return ((int)(this["historySearchWidth3"]));
            }
            set {
                this["historySearchWidth3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historySearchWidth4 {
            get {
                return ((int)(this["historySearchWidth4"]));
            }
            set {
                this["historySearchWidth4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historySearchWidth5 {
            get {
                return ((int)(this["historySearchWidth5"]));
            }
            set {
                this["historySearchWidth5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int historyListWidth5 {
            get {
                return ((int)(this["historyListWidth5"]));
            }
            set {
                this["historyListWidth5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Size orderViewerSize {
            get {
                return ((global::System.Drawing.Size)(this["orderViewerSize"]));
            }
            set {
                this["orderViewerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int orderViewerWidth0 {
            get {
                return ((int)(this["orderViewerWidth0"]));
            }
            set {
                this["orderViewerWidth0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int orderViewerWidth1 {
            get {
                return ((int)(this["orderViewerWidth1"]));
            }
            set {
                this["orderViewerWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int orderViewerWidth2 {
            get {
                return ((int)(this["orderViewerWidth2"]));
            }
            set {
                this["orderViewerWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int orderViewerWidth3 {
            get {
                return ((int)(this["orderViewerWidth3"]));
            }
            set {
                this["orderViewerWidth3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int orderViewerWidth4 {
            get {
                return ((int)(this["orderViewerWidth4"]));
            }
            set {
                this["orderViewerWidth4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("658")]
        public int pontunSplitWidth {
            get {
                return ((int)(this["pontunSplitWidth"]));
            }
            set {
                this["pontunSplitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public int dvRight4Width {
            get {
                return ((int)(this["dvRight4Width"]));
            }
            set {
                this["dvRight4Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int addtop3Width {
            get {
                return ((int)(this["addtop3Width"]));
            }
            set {
                this["addtop3Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double pSizeWidth {
            get {
                return ((double)(this["pSizeWidth"]));
            }
            set {
                this["pSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double pSizeHeight {
            get {
                return ((double)(this["pSizeHeight"]));
            }
            set {
                this["pSizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int orderFinishWidth {
            get {
                return ((int)(this["orderFinishWidth"]));
            }
            set {
                this["orderFinishWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550")]
        public int orderFinishHeight {
            get {
                return ((int)(this["orderFinishHeight"]));
            }
            set {
                this["orderFinishHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int formSelectCategoryWidth {
            get {
                return ((int)(this["formSelectCategoryWidth"]));
            }
            set {
                this["formSelectCategoryWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int formSelectCategoryHeight {
            get {
                return ((int)(this["formSelectCategoryHeight"]));
            }
            set {
                this["formSelectCategoryHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int pSplitWidth {
            get {
                return ((int)(this["pSplitWidth"]));
            }
            set {
                this["pSplitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("850")]
        public int vorugeymslaWidth {
            get {
                return ((int)(this["vorugeymslaWidth"]));
            }
            set {
                this["vorugeymslaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550")]
        public int vorugeymslaHeight {
            get {
                return ((int)(this["vorugeymslaHeight"]));
            }
            set {
                this["vorugeymslaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int viewCustWidth {
            get {
                return ((int)(this["viewCustWidth"]));
            }
            set {
                this["viewCustWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public int viewCustHeight {
            get {
                return ((int)(this["viewCustHeight"]));
            }
            set {
                this["viewCustHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("245")]
        public int viewCustSplit {
            get {
                return ((int)(this["viewCustSplit"]));
            }
            set {
                this["viewCustSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int viewOrdWidth {
            get {
                return ((int)(this["viewOrdWidth"]));
            }
            set {
                this["viewOrdWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int viweOrdHeight {
            get {
                return ((int)(this["viweOrdHeight"]));
            }
            set {
                this["viweOrdHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int historyWidth {
            get {
                return ((int)(this["historyWidth"]));
            }
            set {
                this["historyWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int historyHeight {
            get {
                return ((int)(this["historyHeight"]));
            }
            set {
                this["historyHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 400")]
        public global::System.Drawing.Size historySize {
            get {
                return ((global::System.Drawing.Size)(this["historySize"]));
            }
            set {
                this["historySize"] = value;
            }
        }
    }
}
